### ISSUE TITLE
Submit the repo to https://packagist.org/

### ISSUE THREAD

**Issue by chrisbarr** [what3words/w3w-php-wrapper#4]
Should be pretty straightforward to do, it will ask you to add a git hook to the repo. Means that users will be able to do this:

```
// composer.json
{
  name: "chrisbarr/my-project",
  require: {
    "what3words/w3w-php-wrapper": "~1.0"
  }
}
```

Then run `composer update` and the class will be available via the Composer autoloader like so:

```
<?php
require 'vendor/autoload.php';

$w3w = new what3words('abcdef');
```

The packagist.org page also tracks and shows download stats for the repo.

**Comment by vicchi** [comment]
Done; see https://packagist.org/packages/what3words/w3w-php-wrapper

**Comment by chrisbarr** [comment]
Amazing, thank you!

**Comment by vicchi** [comment]
@chrisbarr Ask and you shall receive; except where void, prohibited by law or in the rare case I haven't had enough coffee.

**Comment by chrisbarr** [comment]
:smile:
